---
kind: pipeline
name: e2e-kubernetes-1.16

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.9.0
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-116
      local_kind_config_path: katalog/tests/istio/kind-config.yml
      instance_size: extra-large
      cluster_version: '1.16.15'
      pipeline_id: cluster-116
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.16.15_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export CLUSTER_NAME=116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/istio/istio-minimal-install.sh
      - bats -t katalog/tests/istio/istio-minimal.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-egress-gateway
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.16.15_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-basic-istio ]
    commands:
      - export CLUSTER_NAME=116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/istio/istio-egress-install.sh
      - bats -t katalog/tests/istio/istio-egress-external-services.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.16.15_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-egress-gateway ]
    commands:
      - export CLUSTER_NAME=116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/istio/istio-citadel-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.16.15_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel ]
    commands:
      - export CLUSTER_NAME=116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/istio/istio-citadel-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.16.15_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel-and-sidecar-injector ]
    commands:
      - export CLUSTER_NAME=116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/istio/istio-minimal-sidecar-injector.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.9.0
    pull: always
    depends_on: [ e2e-basic-istio-and-sidecar-injector ]
    settings:
      action: destroy
      pipeline_id: cluster-116
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}

---
kind: pipeline
name: e2e-kubernetes-1.15

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.9.0
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-115
      local_kind_config_path: katalog/tests/istio/kind-config.yml
      instance_size: extra-large
      cluster_version: '1.15.11'
      pipeline_id: cluster-115
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.15.11_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export CLUSTER_NAME=115
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/istio/istio-minimal-install.sh
      - bats -t katalog/tests/istio/istio-minimal.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-egress-gateway
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.15.11_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-basic-istio ]
    commands:
      - export CLUSTER_NAME=115
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/istio/istio-egress-install.sh
      - bats -t katalog/tests/istio/istio-egress-external-services.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.15.11_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-egress-gateway ]
    commands:
      - export CLUSTER_NAME=115
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/istio/istio-citadel-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.15.11_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel ]
    commands:
      - export CLUSTER_NAME=115
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/istio/istio-citadel-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.15.11_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel-and-sidecar-injector ]
    commands:
      - export CLUSTER_NAME=115
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/istio/istio-minimal-sidecar-injector.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.9.0
    pull: always
    depends_on: [ e2e-basic-istio-and-sidecar-injector ]
    settings:
      action: destroy
      pipeline_id: cluster-115
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}

---
kind: pipeline
name: e2e-kubernetes-1.14

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.9.0
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-114
      local_kind_config_path: katalog/tests/istio/kind-config.yml
      instance_size: extra-large
      cluster_version: '1.14.10'
      pipeline_id: cluster-114
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.14.10_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export CLUSTER_NAME=114
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/istio/istio-minimal-install.sh
      - bats -t katalog/tests/istio/istio-minimal.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-egress-gateway
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.14.10_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-basic-istio ]
    commands:
      - export CLUSTER_NAME=114
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/istio/istio-egress-install.sh
      - bats -t katalog/tests/istio/istio-egress-external-services.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.14.10_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-egress-gateway ]
    commands:
      - export CLUSTER_NAME=114
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/istio/istio-citadel-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-istio-with-citadel-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.14.10_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel ]
    commands:
      - export CLUSTER_NAME=114
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/istio/istio-citadel-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-sidecar-injector-install.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-1.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-2.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-3.sh
      - bats -t katalog/tests/istio/istio-citadel-authn-cleanup.sh
      - bats -t katalog/tests/istio/istio-citadel-rollback.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: e2e-basic-istio-and-sidecar-injector
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.14.10_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ e2e-istio-with-citadel-and-sidecar-injector ]
    commands:
      - export CLUSTER_NAME=114
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/istio/istio-minimal-sidecar-injector.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.9.0
    pull: always
    depends_on: [ e2e-basic-istio-and-sidecar-injector ]
    settings:
      action: destroy
      pipeline_id: cluster-114
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}
