istio_namespace: istio-system
deployment:
  accessible_namespaces: ['**']
auth:
  strategy: anonymous
server:
  port: 20001
  web_root: /kiali
external_services:
  tracing:
    url:
  grafana:
    url:
  prometheus:
    url: http://prometheus-k8s.monitoring:9090
