---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

images:
  - name: docker.io/jaegertracing/all-in-one
    newTag: "1.14"

bases:
  - ../minimal

resources:
  - deploy.yml
  - service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: istio
    namespace: istio-system
    behavior: merge
    files:
      - mesh=config/mesh.yml
