---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

images:
  - name: docker.io/jaegertracing/all-in-one
    newName: registry.sighup.io/fury/jaegertracing/all-in-one
    newTag: "1.14"
  - name: docker.io/istio/proxyv2
    newName: registry.sighup.io/fury/istio/proxyv2
    newTag: "1.4.2"
  - name: docker.io/istio/pilot
    newName: registry.sighup.io/fury/istio/pilot
    newTag: "1.4.2"
  - name: docker.io/istio/mixer
    newName: registry.sighup.io/fury/istio/mixer
    newTag: "1.4.2"

bases:
  - ../minimal

resources:
  - deploy.yml
  - service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: istio
    namespace: istio-system
    behavior: merge
    files:
      - mesh=config/mesh.yml
