apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-tracing
spec:
  replicas: 2 # Using elasticsearch is possible to scale the deployment to > 1 replica
  template:
    spec:
      volumes:
        - name: data
          $patch: delete
      containers:
        - name: jaeger
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          # ElasticSearch related environments. More information: https://www.jaegertracing.io/docs/1.14/deployment/#elasticsearch
          - name: SPAN_STORAGE_TYPE
            value: "elasticsearch"
          - name: ES_SERVER_URLS
            value: "http://elasticsearch.logging.svc.cluster.local:9200"
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: "9411"
          - name: MEMORY_MAX_TRACES
            value: "50000"
          - name: QUERY_BASE_PATH
            value:  /jaeger
          volumeMounts:
          - mountPath: /badger
            $patch: delete
